### ISSUE TITLE
The styles tab is blocked by the passage editor windows.

### ISSUE THREAD

**Issue by ImmortalAI** [klembot/twinejs#1399]
### Describe the bug.

![image](https://github.com/klembot/twinejs/assets/133595975/2292a44a-f03e-4c03-8f8b-96f8868852a7)

Window with additional styles is blocked by other windows.

### Steps to reproduce:

Open multiple passages for editing, in "Styles" open "More styles..."
Well done, now close all editor windows except last to use custom styles.

### Expected behavior:

In previous versions it worked correctly, window with styles was visible for the active passage editor.

### Twine version number

2.6.2

### Does this problem occur with the web version of Twine or the desktop app?

Web

### What operating system does this problem occur on?

Windows

### If this problem is occurring with the web version of Twine, what browser does it occur on?

Chrome/Chromium

### Presubmission checklist

- [ ] I am interested in working on code that would fix this bug. (This is not required to submit a bug report.)
- [X] I have done a search and believe that an issue does not already exist for this bug in the GitHub repository.
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by greyelf** [comment]
Harlowe itself is responsible for adding the custom toolbar to the **Passage Editor** window, and for displaying the **Example Text Preview** dialog when the **More Style...** item is selected in that custom toolbar's **Styles** menu.

It appears that Harlowe always attaches the **harloweToolbar** classed `<div>` element to the Passage Editor that is 'deepest' in the stack of 'open' Passages, even when the **Styles** option selected belonged to the 'nearest' Passage Editor. Which results in the child **harlowe-3-toolbarPanel** classed `<div>` element being used to display the **Example Text Preview** dialog to appear 'above' that 'deepest' Passage Editor instead of the 'nearest'.

I could be wrong, but as far as I can tell this is a Harlowe specific issue and not a Twine 2.x application one, which means it would need to be reported on the [Harlowe project's Issue page](https://foss.heptapod.net/games/harlowe/-/issues).
