### ISSUE TITLE
Numeric Variables - Internal Error

### ISSUE THREAD

**Issue by lunik11** [klembot/twinejs#1501]
### Describe the bug.

The latest version of Harlowe (3.3.7) can't internalize and apply numeric variables. The following bug appears when I play test the game: 

An internal error occurred while trying to run (set: $success += 1).

I don't believe the code for the variable is wrong and this is a recurring issue. I've restarted Twine as well as re-uploaded the game, but this error continues to occur. 

### Steps to reproduce:

Insert the following variable in the room: 

(set: $success += 1).

Make at least four subsequent rooms with the above variable equal to 4. In the fifth room, add the following variable:

(if: $success is >4)

### Expected behavior:

No errors should occur and the fifth and final room should appear in the specific text. 

### Twine version number

3.3.7

### Does this problem occur with the web version of Twine or the desktop app?

Desktop app

### What operating system does this problem occur on?

Android

### If this problem is occurring with the web version of Twine, what browser does it occur on?

None

### Presubmission checklist

- [ ] I am interested in working on code that would fix this bug. (This is not required to submit a bug report.)
- [X] I have done a search and believe that an issue does not already exist for this bug in the GitHub repository.
- [X] If this problem is occurring with the app version of Twine, it still happens after I remove the `user.css` file from my Twine folder. (You would've added this file yourself. If you don't understand this question, you can safely check this box.)
- [X] I have read and agree to abide by this project's Code of Conduct.

**Comment by greyelf** [comment]
@lunik11 
Your question relates to what a specific Story Format (in this case Harlowe) is doing with the content you've placed in a Passage.

And such questions are better asked in a Twine related [Discord server](https://discordapp.com/invite/n5dJvPp) or forum (like [Intfiction](https://intfiction.org/) or [Reddit](https://www.reddit.com/r/twinegames/)).

This is the Twine 2.x application's repository, and the application itself does not process or execute the contents of a Passage.

But to answer your question...

> An internal error occurred while trying to run `(set: $success += 1)`.

The [Number](https://twine2.neocities.org/#type_number) data section of the Harlowe 3.x documentation lists all the mathematical and keyword operators that can be used with a Number, and the JavaScript based [Addition assignment +=](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Addition_assignment) operator is not listed.

Nor are any of the other JavaScript mathematical assignment or equality operators, as Harlowe doesn't support them either.

The correct syntax for preform an addition assignment in Harlowe is to us the [`it`](Addition assignment) keyword like so...
```
(set: $success to it + 1)
```

> add the following variable:
> ```(if: $success is >4)```

While the above comparison won't product an error (a) it is syntaxy and logically invalid, because:

- the **`is`** keyword comparison operator represents `exactly equal to`
- the **`>`** mathematical comparison operator represents `left-side is greater than right-side`
- a two values can't logically be both `exactly equal to` and `left-side is greater than right-side` at the same time

The same logic issue is true when combining the **`is`** keyword comparison operator with any of the mathematical comparison operator,

The correct syntax for a `left-side is greater than right-side` comparison is...
```
(if: $success > 4)
```
(a) because Harlowe 3.x was changed to ignore that class of syntax errors.

**Comment by lunik11** [comment]
@greyelf 
Thank you very much for clarifying this issue for me. My apologies for not posting this issue on the correct webpage. I'll be sure to keep this in mind for the future!
