### ISSUE TITLE
Twine 2 opens than closes.

### ISSUE THREAD

**Issue by power12359** [klembot/twinejs#535]
I installed Twine 2. When I try to open it, it gives me a white screen. Then it closes itself.

There was a text file called debug. This is what was in it.

[0321/015831.602:ERROR:http_transport_win.cc(170)] WinHttpCrackUrl: The URL does not use a recognized protocol  (0x2ee6)

**Comment by HiEv** [comment]
This is usually caused by a corrupted "User Data" folder.
If you're using Windows that will be in "C:\Users\YourUserName\AppData\Local\Twine\" (replace "YourUserName" with your Windows user name.  To fix the problem:
1. Make sure Twine is closed.
2. Rename the "User Data" folder there to something else.
3. Open Twine to see if it works now.
4. If Twine works you can delete the renamed "User Data" folder.  If not you can put it back if you want to.

That works most of the time with this problem.

**Comment by power12359** [comment]
Your solution worked. Thank you very much.
