### ISSUE TITLE
Haunted by stories

### ISSUE THREAD

**Issue by Derynian** [klembot/twinejs#670]
Twine 2.3.5. on Chapbook 1

Months ago I created a story called Test.

After I duplicated it, two stories titled Test appeared in the story list.
I erased the two stories (actually I erased one, the other immediately disappeared on its own).
 
The following day the two stories reappeared in the list of stories.

I deleted them again, but they always reappear. I emptied them from the passages, they reappear again. I have repeatedly cleaned the cache, with no effect.

Today I tried to rename one, the two test stories have disappeared. I closed and opened twine again and ..... now I have three Test stories!

Could anyone help me please?

Thanks for the attention.

Derynian

P.S.
I attach screenshots

![three-stories](https://user-images.githubusercontent.com/65771042/82671400-135dab80-9c3f-11ea-81e5-14803be3b022.jpg)

**Comment by HiEv** [comment]
Unfortunately, this is a problem caused by one known bug (#639), where the internal names of stories don't get updated properly when renaming them, which then triggers another known bug (#628) where undeletable duplicates of stories start appearing.  (See also #615, #644, and #665.)

Until this is fixed, I'd recommend avoiding using the "**Rename Story**" or "**Duplicate Story**" methods within Twine, and you also shouldn't import an HTML file which has an internal name which matches a story already in your version of Twine. (The "internal name" is the one found within `<tw-storydata name="(internal name here)"` inside the HTML.)

If you need to duplicate or rename a story, you should export the HTML with the new filename you want, then edit the HTML in a decent text editor (like [Notepad++](https://notepad-plus-plus.org/)) to change the internal name to match that new name you want, save it, and then import that HTML into Twine.  (You may also want to change the file's IFID as well while you're doing that.)

To fix the problems with the duplicates, you'll need to [follow the steps I laid out](https://github.com/klembot/twinejs/issues/628#issuecomment-565784557) within bug report #628.

Hope that helps!  :smile:

**Comment by Derynian** [comment]
Hi  HiEv ,

Thanks for your reply. I made what you suggested, and all works fine! Thanks a lot. From now  never more i will rename/duplicate a story.

Thanks again.

Derynian
