### ISSUE TITLE
Twine 2 Version 2.3.7: Story resets to an old save file

### ISSUE THREAD

**Issue by VoxNihili2411** [klembot/twinejs#676]
Hi there,

I've been working on a story for a while now but unfortunately, when I attempted to open the file again today I encountered a bit of an issue.

About half the story no longer existed, it just stopped at an old save file never to be seen again. I've been using the downloadable version of twine that is currently in version 2.3.7. What's interesting is that the file saved fine the day before, and I was able to get all my progress back but opening it today revealed that the file was now back to where I was around last week.

I was hoping is there any way you can retrieve my work? I need it because we are using twine for a university assignment and it's due tomorrow. I might be able to get an extension if I know exactly what went wrong and or simply get my progress back.

I quick response would be appreciated!

**Comment by VoxNihili2411** [comment]
Oooh ok, I think I've fixed it.

I had to delete all my stories and reupload then into twine.

I think it was because the titles of my stories were too similar. I knew you couldn't name them the same thing but apparently you can't name them something similar either. I was resaving my story Version 1, 1.1, 1.2, 1.3 Etc but as I was reading through some of the other issues people have encountered it becomes obvious that twine doesn't actually register the name of something after putting in a full stop. So when I naming my files 1.2, 1.3, 1.4 etc twine only saw the 1 and thought they were the same.

**Comment by HiEv** [comment]
Unfortunately, this is a problem caused by one known bug (#639), where the internal names of stories don't get updated properly when renaming them, which then triggers another known bug (#628) where undeletable duplicates of stories start appearing. (See also #615, #644, and #665.)

Until this is fixed, I'd recommend avoiding using the "**Rename Story**" or "**Duplicate Story**" methods within Twine, and you also shouldn't import an HTML file which has an internal name which matches a story already in your version of Twine. (The "internal name" is the one found within `<tw-storydata name="(internal name here)"` inside the HTML.)

If you need to duplicate or rename a story, you should export the HTML with the new filename you want, then edit the HTML in a decent text editor (like [Notepad++](https://notepad-plus-plus.org/)) to change the internal name to match that new name you want, save it, and then import that HTML into Twine. (You may also want to change the file's IFID as well while you're doing that.)

If you're using the offline version of Twine, to fix the problems with the duplicates you may need to [follow the steps I laid out](https://github.com/klembot/twinejs/issues/628#issuecomment-565784557) within bug report #628.

Hope that helps! smile

**Comment by greyelf** [comment]
> I was resaving my story...
> So when I naming my files..

How exactly are you "resaving" / "naming" your story?
eg. Are you making a copy of the story project HTML file within your Operating System's File Manager and then renaming that file? Are you using the Twine 2.x application's built-in features to make the copy? Some other method?
