### ISSUE TITLE
(dropdown:) displaying with a white background in Chrome

### ISSUE THREAD

**Issue by tamehistorian** [klembot/twinejs#816]
Dropdown lists work fine in Firefox, but in Chrome they open with a white background regardless of the styling of the rest of the passage which means that text often isn't visible.

Code used:
`(dropdown: 2bind $program,"Education Track - Mentoring Class","Skills Track - Bike Repairs","Work Track - Kitchen Facilities")`

Result in Chrome:
![image](https://user-images.githubusercontent.com/82881484/115392048-0d1dd980-a1d8-11eb-92ff-162009250059.png)

Any ideas would be appreciated! Thanks!

**Comment by HiEv** [comment]
This isn't a Twine issue, it's caused by the CSS in the Harlowe story format, so you'll simply need to look for the appropriate CSS to change how that's displayed.

If you need help with that, I'd recommend asking at one of the following locations:
[IntFiction - Twine section](https://intfiction.org/c/authoring/twine/46)
[Reddit - r/twinegames](https://www.reddit.com/r/twinegames/)
[Discord - Twine](https://discord.gg/n5dJvPp)

**Comment by greyelf** [comment]
@tamehistorian 
As explained by HiEv, the issue you're reporting is caused by Harlowe's default CSS. I suggest [reporting that issue](https://foss.heptapod.net/games/harlowe/-/issues) on the Harlowe project's [Heptapod repository](https://foss.heptapod.net/games/harlowe).
